apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  namespace: default
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  selector:
    app: netflix-app
  ports:
    - name: http
      port: 80
      targetPort: 80
